[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--prefix project"
  NPM_VERSION = "8.19.4"
  YARN_VERSION = "1.22.19"
  PNPM_VERSION = "8.15.6"
  NODE_VERSION = "18"
